blueprint:
  name: LeTv remote
  description: "Blueprint for LeTv 8key remote(Zigbee2MQTT)"
  domain: automation
  input:
    switch:
      name: LeTv 8key remote
      description: LeTv 8key remote to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
    button_1_single:
      name: Single Press - Back
      description: Action to run on button 1 single press
      default: []
      selector:
        action: null
    button_1_hold:
      name: Hold - Back
      description: Action to run on button 1 long press
      default: []
      selector:
        action: null
    button_1_double:
      name: Double Press - Back
      description: Action to run on button 1 double press
      default: []
      selector:
        action: null
    button_1_release:
      name: Release - Back
      description: Action to run release button 1
      default: []
      selector:
        action: null
    button_2_single:
      name: Single Press - Button 2
      description: Action to run on button 2 single press
      default: []
      selector:
        action: null
    button_2_hold:
      name: Hold - Button 2
      description: Action to run on button 2 long press
      default: []
      selector:
        action: null
    button_2_double:
      name: Double Press - Button 2
      description: Action to run on button 2 double press
      default: []
      selector:
        action: null
    button_3_single:
      name: Single Press - Button 3
      description: Action to run on button 3 single press
      default: []
      selector:
        action: null
    button_3_hold:
      name: Hold - Button 3
      description: Action to run on button 3 long press
      default: []
      selector:
        action: null
    button_3_double:
      name: Double Press - Button 3
      description: Action to run on button 3 double press
      default: []
      selector:
        action: null
    button_4_single:
      name: Single Press - Button 4
      description: Action to run on button 4 single press
      default: []
      selector:
        action: null
    button_4_hold:
      name: Long Press - Button 4
      description: Action to run on button 4 long press
      default: []
      selector:
        action: null
    button_4_double:
      name: Double Press - Button 4
      description: Action to run on button 4 double press
      default: []
      selector:
        action: null

mode: queued

trigger:
  - platform: state
    entity_id: !input switch

condition:
  - "{{ trigger.to_state.state != '' }}"

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'button_1_single' }}"
        sequence: !input button_1_single 
      - conditions:
          - "{{ command == 'button_1_double' }}"
        sequence: !input button_1_double
      - conditions:
          - "{{ command == 'button_1_hold' }}"
        sequence: !input button_1_hold
      - conditions:
          - "{{ command == 'button_1_release' }}"
        sequence: !input button_1_release
      - conditions:
          - "{{ command == 'button_2_single' }}"
        sequence: !input button_2_single
      - conditions:
          - "{{ command == 'button_2_double' }}"
        sequence: !input button_2_double
      - conditions:
          - "{{ command == 'button_2_hold' }}"
        sequence: !input button_2_hold
      - conditions:
          - "{{ command == 'button_2_release' }}"
        sequence: !input button_2_release
      - conditions:
          - "{{ command == 'button_3_single' }}"
        sequence: !input button_3_single
      - conditions:
          - "{{ command == 'button_3_double' }}"
        sequence: !input button_3_double
      - conditions:
          - "{{ command == 'button_3_hold' }}"
        sequence: !input button_3_hold
      - conditions:
          - "{{ command == 'button_3_release' }}"
        sequence: !input button_3_release
      - conditions:
          - "{{ command == 'button_4_single' }}"
        sequence: !input button_4_single
      - conditions:
          - "{{ command == 'button_4_double' }}"
        sequence: !input button_4_double
      - conditions:
          - "{{ command == 'button_4_hold' }}"
        sequence: !input button_4_hold
      - conditions:
          - "{{ command == 'button_4_release' }}"
        sequence: !input button_4_release