blueprint:
  name: LeTv remote
  description: "Blueprint for LeTv 8key remote(Zigbee2MQTT)"
  domain: automation
  input:
    switch:
      name: LeTv 8key remote
      description: LeTv 8key remote to use
      selector:
        entity:
          domain: sensor
          integration: mqtt
    button_1_single:
      name: Single Press - Back
      description: Action to run on button 1 single press
      default: []
      selector:
        action: null
    button_1_hold:
      name: Hold - Back
      description: Action to run on button 1 long press
      default: []
      selector:
        action: null
    button_1_double:
      name: Double Press - Back
      description: Action to run on button 1 double press
      default: []
      selector:
        action: null
    button_1_release:
      name: Release - Back
      description: Action to run release button 1
      default: []
      selector:
        action: null
    button_2_single:
      name: Single Press - Down
      description: Action to run on button 2 single press
      default: []
      selector:
        action: null
    button_2_hold:
      name: Hold - Down
      description: Action to run on button 2 long press
      default: []
      selector:
        action: null
    button_2_double:
      name: Double Press - Down
      description: Action to run on button 2 double press
      default: []
      selector:
        action: null
    button_2_release:
      name: Release - Down
      description: Action to run release button 2
      default: []
      selector:
        action: null
    button_3_single:
      name: Single Press - Right
      description: Action to run on button 3 single press
      default: []
      selector:
        action: null
    button_3_hold:
      name: Hold - Right
      description: Action to run on button 3 long press
      default: []
      selector:
        action: null
    button_3_double:
      name: Double Press - Right
      description: Action to run on button 3 double press
      default: []
      selector:
        action: null
    button_3_release:
      name: Release - Right
      description: Action to run release button 3
      default: []
      selector:
        action: null
    button_4_single:
      name: Single Press - Up
      description: Action to run on button 4 single press
      default: []
      selector:
        action: null
    button_4_hold:
      name: Long Press - Up
      description: Action to run on button 4 long press
      default: []
      selector:
        action: null
    button_4_double:
      name: Double Press - Up
      description: Action to run on button 4 double press
      default: []
      selector:
        action: null
    button_4_release:
      name: Release - Up
      description: Action to run release button 4
      default: []
      selector:
        action: null
    button_5_single:
      name: Single Press - Left
      description: Action to run on button 5 single press
      default: []
      selector:
        action: null
    button_5_hold:
      name: Long Press - Left
      description: Action to run on button 5 long press
      default: []
      selector:
        action: null
    button_5_double:
      name: Double Press - Left
      description: Action to run on button 5 double press
      default: []
      selector:
        action: null
    button_5_release:
      name: Release - Left
      description: Action to run release button 5
      default: []
      selector:
        action: null
    button_6_single:
      name: Single Press - Mic
      description: Action to run on button 6 single press
      default: []
      selector:
        action: null
    button_6_hold:
      name: Long Press - Mic
      description: Action to run on button 6 long press
      default: []
      selector:
        action: null
    button_6_double:
      name: Double Press - Mic
      description: Action to run on button 6 double press
      default: []
      selector:
        action: null
    button_6_release:
      name: Release - Mic
      description: Action to run release button 6
      default: []
      selector:
        action: null
    button_7_single:
      name: Single Press - Play/Pause
      description: Action to run on button 7 single press
      default: []
      selector:
        action: null
    button_7_hold:
      name: Long Press - Play/Pause
      description: Action to run on button 7 long press
      default: []
      selector:
        action: null
    button_7_double:
      name: Double Press - Play/Pause
      description: Action to run on button 7 double press
      default: []
      selector:
        action: null
    button_7_release:
      name: Release - Play/Pause
      description: Action to run release button 7
      default: []
      selector:
        action: null
    button_8_single:
      name: Single Press - Ok
      description: Action to run on button 8 single press
      default: []
      selector:
        action: null
    button_8_hold:
      name: Long Press - Ok
      description: Action to run on button 8 long press
      default: []
      selector:
        action: null
    button_8_double:
      name: Double Press - Ok
      description: Action to run on button 8 double press
      default: []
      selector:
        action: null
    button_8_release:
      name: Release - Ok
      description: Action to run release button 8
      default: []
      selector:
        action: null

mode: queued

trigger:
  - platform: state
    entity_id: !input switch

condition:
  - "{{ trigger.to_state.state != '' }}"

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'button_1_single' }}"
        sequence: !input button_1_single 
      - conditions:
          - "{{ command == 'button_1_double' }}"
        sequence: !input button_1_double
      - conditions:
          - "{{ command == 'button_1_hold' }}"
        sequence: !input button_1_hold
      - conditions:
          - "{{ command == 'button_1_release' }}"
        sequence: !input button_1_release
      - conditions:
          - "{{ command == 'button_2_single' }}"
        sequence: !input button_2_single
      - conditions:
          - "{{ command == 'button_2_double' }}"
        sequence: !input button_2_double
      - conditions:
          - "{{ command == 'button_2_hold' }}"
        sequence: !input button_2_hold
      - conditions:
          - "{{ command == 'button_2_release' }}"
        sequence: !input button_2_release
      - conditions:
          - "{{ command == 'button_3_single' }}"
        sequence: !input button_3_single
      - conditions:
          - "{{ command == 'button_3_double' }}"
        sequence: !input button_3_double
      - conditions:
          - "{{ command == 'button_3_hold' }}"
        sequence: !input button_3_hold
      - conditions:
          - "{{ command == 'button_3_release' }}"
        sequence: !input button_3_release
      - conditions:
          - "{{ command == 'button_4_single' }}"
        sequence: !input button_4_single
      - conditions:
          - "{{ command == 'button_4_double' }}"
        sequence: !input button_4_double
      - conditions:
          - "{{ command == 'button_4_hold' }}"
        sequence: !input button_4_hold
      - conditions:
          - "{{ command == 'button_4_release' }}"
        sequence: !input button_4_release
      - conditions:
          - "{{ command == 'button_5_single' }}"
        sequence: !input button_5_single
      - conditions:
          - "{{ command == 'button_5_double' }}"
        sequence: !input button_5_double
      - conditions:
          - "{{ command == 'button_5_hold' }}"
        sequence: !input button_5_hold
      - conditions:
          - "{{ command == 'button_5_release' }}"
        sequence: !input button_5_release
      - conditions:
          - "{{ command == 'button_6_single' }}"
        sequence: !input button_6_single
      - conditions:
          - "{{ command == 'button_6_double' }}"
        sequence: !input button_6_double
      - conditions:
          - "{{ command == 'button_6_hold' }}"
        sequence: !input button_6_hold
      - conditions:
          - "{{ command == 'button_6_release' }}"
        sequence: !input button_6_release
      - conditions:
          - "{{ command == 'button_7_single' }}"
        sequence: !input button_7_single
      - conditions:
          - "{{ command == 'button_7_double' }}"
        sequence: !input button_7_double
      - conditions:
          - "{{ command == 'button_7_hold' }}"
        sequence: !input button_7_hold
      - conditions:
          - "{{ command == 'button_7_release' }}"
        sequence: !input button_7_release
      - conditions:
          - "{{ command == 'button_8_single' }}"
        sequence: !input button_8_single
      - conditions:
          - "{{ command == 'button_8_double' }}"
        sequence: !input button_8_double
      - conditions:
          - "{{ command == 'button_8_hold' }}"
        sequence: !input button_8_hold
      - conditions:
          - "{{ command == 'button_8_release' }}"
        sequence: !input button_8_release
