blueprint:
  name: Zigbee2MQTT - Tuya Smart Button SH-SC07
  description: Tuya Zigbee 1-Button Scene Switch
  domain: automation
  input:
    switch:
      name: Tuya Smart Button
      description: Zigbee2MQTT Name SH-SC07
      selector:
        entity:
          domain: sensor
          integration: mqtt
      
    event_single:
      name: Event | Single Press
      description: Action to run on single press in event mode
      default: []
      selector:
        action: null
    event_double:
      name: Event | Double Press
      description: Action to run on double press in event mode
      default: []
      selector:
        action: null
    event_hold:
      name: Event | Hold Press
      description: Action to run on hold press in event mode
      default: []
      selector:
        action: null

mode: queued

trigger:
  - platform: state
    entity_id: !input switch

condition:
  - "{{ trigger.to_state.state != '' }}"

action:
  - variables:
      command: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ command == 'single' }}"
        sequence: !input event_single
      - conditions:
          - "{{ command == 'double' }}"
        sequence: !input event_double
      - conditions:
          - "{{ command == 'hold' }}"
        sequence: !input event_hold
