blueprint:
  name: Zigbee2MQTT - Tuya Smart Button SH-SC07
  description: Tuya Zigbee 1-Button Scene Switch
  domain: automation
  input:
    mqtt_entity:
      description: Zigbee2MQTT Name SH-SC07
      name: Name
    base_topic:
      description: The base topic as defined in the zigbee2mqtt config
      default: zigbee2mqtt
      name: Base Topic
      selector:
        entity:
          domain: sensor
          integration: mqtt
      
    event_single:
      name: Event | Single Press
      description: Action to run on single press in event mode
      default: []
      selector:
        action: null
    event_double:
      name: Event | Double Press
      description: Action to run on double press in event mode
      default: []
      selector:
        action: null
    event_hold:
      name: Event | Hold Press
      description: Action to run on hold press in event mode
      default: []
      selector:
        action: null
