blueprint:
  name: Zigbee2MQTT - Smart_Button
  description: Tuya Zigbee 1-Button Scene Switch
  domain: automation
  input:
    mqtt_entity:
      description: The "friendly" SH-SC07 device name as is registered in zigbee2mqtt
      name: Name
    base_topic:
      description: The base topic as defined in the zigbee2mqtt config
      default: zigbee2mqtt
      name: Base Topic
      
    event_single:
      name: Event | Single Press
      description: Action to run on single press in event mode
      default: []
      selector:
        action: {}
    event_double:
      name: Event | Double Press
      description: Action to run on double press in event mode
      default: []
      selector:
        action: {}
    event_hold:
      name: Event | Hold Press
      description: Action to run on hold press in event mode
      default: []
      selector:
        action: {}
